### ISSUE TITLE
install_hash should support arrays 

### ISSUE THREAD

**Issue by logicminds** [example42/puppet-tp#44]
## Expected Behavior 
Install_hash parameter should accept arrays.  I would expect that when I use hieradata to specify multiple apps I want installed that I can easily supply an array.

Example:

```
tp::install_hash: 
  - redis
  - bash
  - iotop
```

## Actual Behavior
  install_hash is limited to just hashes.

```
tp::install_hash: 
  redis:
    ensure: present
  bash:
    ensure: present
  iotop:
    ensure: present
```

## Possible Fix
If we change the datatype to `Variant[Hash,Array[String]]` we can at least accept both hashes and arrays.

Furthermore, we would also have to do something like:

```puppet
if $install_hash =~ Array {
  $installables = $install_hash.map | $name| { tp_install($name, {ensure => present}) }
} else {
  $installables = $install_hash.map | $name, $options| { tp_install($name, $options) }
}
```
