### ISSUE TITLE
tp::install is failing when defining configuration file source in conf_hash

### ISSUE THREAD

**Issue by findmyname666** [example42/puppet-tp#70]
## Expected Behavior 
To Create configuration file.

## Actual Behavior
The code is failing on:
```
Error: Validation of File[/etc/process-exporter/config.yaml] failed: You cannot specify more than one of content, source, target (file: /etc/puppetlabs/code/environments/production/modules/tp/manifests/conf.pp, line: 339)
```

With added logging:
```
--- /etc/puppetlabs/code/environments/production/modules/tp/manifests/conf.pp	2020-02-19 15:33:25.591810484 +0000
+++ /tmp/conf.pp	2020-02-19 15:33:18.343745299 +0000
@@ -333,6 +333,8 @@
     notify       => $manage_notify,
     validate_cmd => $manage_validate_cmd,
   }
+  $config_file_parameters = pick($settings[config_file_params],{})
+  notice("path: ${manage_path},file params: ${file_params}, config file parameters: ${config_file_parameters} ")
 
   file { $manage_path:
     * => $file_params + pick($settings[config_file_params],{})
```
We can see that there are really source and content in var **$file_params** but content is empty.
```
Notice: Scope(Tp::Conf[prometheus-process-exporter]): path: /etc/process-exporter/config.yaml,file params: {ensure => latest, source => puppet:///site/showmax_tinydata/prometheus-process-exporter, content => , path => /etc/process-exporter/config.yaml, mode => 0644, owner => root, group => root, require => Package[prometheus-process-exporter], notify => Service[prometheus-process-exporter], validate_cmd => }, config file parameters: {}
```

## Steps to Reproduce the Problem

  1. Pass following data to **tp::install**:
```
packages:
  prometheus-process-exporter:
    ensure: 'latest'
    data_module: 'my_tinydata'
    conf_hash:
      'prometheus-process-exporter':
         source: 'puppet:///site/my_tinydata/prometheus-process-exporter'
```

When i change ensure to present everything works + when i passed ensure to conf_hash:
```
  prometheus-process-exporter:
    ensure: 'latest'
    data_module: 'showmax_tinydata'
    conf_hash:
      prometheus-process-exporter:
        ensure: 'file'
        source: 'puppet:///modules/showmax_tinydata/prometheus-process-exporter/nginx.yaml'
```
 
  2. Execute tp::install
```
  $packages.each |$package_name, $attributes| {
    tp::install { $package_name:
      * => $attributes,
    }
  }
``` 

FYI my tinydata:
```
---
  prometheus-process-exporter::settings:
    package_name: 'prometheus-process-exporter'
    service_name: 'prometheus-process-exporter'
    config_file_path: '/etc/process-exporter/config.yaml'
```

## Specifications

Please add this info:

 - Running on Debian9
 - TP module version **2.4.1**
